### ISSUE TITLE
Link to emojis.csv out of date

### ISSUE THREAD

**Issue by JontySinai** [today-is-a-good-day/emojis#1]
Hi Jessica, 

Your work on emoji's is brilliant and I am experimenting with a similar analysis. One issue though:

The link in line 123 of emoji_analysis.R appears to be out of date. Following the link leads to an empty page.

**Comment by hamdanazhar** [comment]
seconding this issue! thank you :)

**Comment by today-is-a-good-day** [comment]
Thanks :) Apparently Felipe took the emojis list down. I uploaded the csv file to my repo and changed the link in the script, it should work now.
