### ISSUE TITLE
Urgently help

### ISSUE THREAD

**Issue by Iris0904** [today-is-a-good-day/emojis#3]
After I run this code，
rank <- emojis_matching(usermedia$text, matchto, description) %>%
group_by(description) %>%
summarise(n = sum(count)) %>%
arrange(-n)

I find all the description count and sentiment are NA.
![image](https://user-images.githubusercontent.com/51853537/59551268-046e7380-8f6f-11e9-8e00-612a1973c176.png)

**Comment by today-is-a-good-day** [comment]
That means the function `emojis_matching()` couldn't match anything/find any emojis and this happens for different reasons. Maybe there are no emojis in the tweets (the pic you added for example doesn't contain any emojis at first sight, makes sense in a political context to not go rogue with emojis). Maybe the list of emojis and/or the sentiments list used in the code is outdated and thus cannot match newer emojis. From wat you have posted, it is not possible to say for sure what happened. 

If you provide a reproducible example, I can look into it. I will close the issue for now.
